[package]
name = "monta_kafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pkg-config = "0.3.26"