root = "."
tmp_dir = "tmp"

[build]
cmd = "GOEXPERIMENT=greenteagc go build -o ./tmp/trenova-cli ./cmd/cli"
bin = "./tmp/trenova-cli"
delay = 100
exclude_dir = ["assets", "tmp", "vendor", "ui", "platform", "microservices"]
include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
exclude_regex = ["_test\\.go"]
send_interrupt = false
stop_on_error = true
